sudo: required
dist: trusty
language: java
jdk:
    - openjdk8
    - oraclejdk8
    - oraclejdk9

services:
    - docker
before_install:
     - echo 'Installing boost-common lib from my fork ....'
     - git clone https://github.com/scottkurz/boost-common.git ./boost-common
     - cd ./boost-common
     - git checkout read-server.address-prop 
     - mvn clean install
     - cd ..
     - docker run -d -p 5000:5000 --restart=always --name registry registry:2
install: true
script:
  - travis_wait mvn verify -Pit -Dinvoker.streamLogs=true
